server:
  port: 8080

nvr:
  # 开发环境建议使用相对可写目录，避免权限问题
  hlsRoot: ./streams
  ffmpeg: /usr/bin/ffmpeg
  hls:
    time: 2          # 每段 2s，更稳
    listSize: 10     # 保留 10 段（≈20s 窗口）
    deleteSegments: false  # 开发环境先不删，避免客户端追不上
    aacBitrate: 96k
  ffmpegFlags: "-rtsp_transport tcp -rtsp_flags prefer_tcp -analyzeduration 10000000 -probesize 20000000 -fflags nobuffer+genpts"

spring:
  mvc:
    cors:
      mappings:
        - path-pattern: "/**"
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"
